# Generated by Django 3.2.2 on 2021-07-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.CharField(max_length=512, unique=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_profile', models.SmallIntegerField(default=0)),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(default='2fb78a81-8374-4bf4-8f6b-d91a9b694f00', max_length=50, unique=True)),
                ('pw', models.CharField(default='02ffc430-2c6d-45fe-b9bf-bf27c38fc0b8', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nick_name', models.CharField(max_length=32, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=16, null=True, unique=True)),
                ('status', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='picon.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_pick', to='picon.user')),
                ('to_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_pick', to='picon.file')),
            ],
            options={
                'db_table': 'pick',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=1)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_follow', to='picon.user')),
                ('to_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_follow', to='picon.user')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='picon.user'),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='heart', max_length=10)),
                ('status', models.SmallIntegerField(default=1)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('from_feed_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_feed_back', to='picon.user')),
                ('to_feed_back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_feed_back', to='picon.file')),
            ],
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('from_follow', 'to_follow'), name='unique_relation'),
        ),
    ]
