# Generated by Django 3.2.5 on 2021-07-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='index_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pw',
        ),
    ]
