# Generated by Django 3.2.2 on 2021-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='index_name',
            field=models.CharField(default='1ca99b91-368e-438a-bf8d-6505185b440d', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(default='bed8a091-cfd2-45be-807b-60c61fd6ac00', max_length=50),
        ),
    ]
