# Generated by Django 3.2.2 on 2021-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picon', '0002_auto_20210718_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='index_name',
            field=models.CharField(default='0eea93b8-d187-445b-b743-7251ac6952fa', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(default='8315695e-3e68-4953-98e3-7b5d8c747dae', max_length=50),
        ),
    ]
