# Generated by Django 3.2.2 on 2021-07-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picon', '0003_auto_20210718_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='edef0c1d-66fb-42f9-8ec2-b31e76783663', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='index_name',
            field=models.CharField(default='c45d964e-2c14-4335-a65b-027a68204f30', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='eea26a63-fc9a-4d41-a41a-e363112ee1ca', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw',
            field=models.CharField(default='d49bab9e-1819-4d2e-9c71-08c5620e6ee8', max_length=50),
        ),
    ]
