# Generated by Django 3.2.2 on 2021-07-18 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picon', '0005_auto_20210718_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator('^0[0-9]{2}-[0-9]{4}-[0-9]{4}$', '유효하지 않은 전화번호 형식입니다.')]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(19|20)[0-9]{2}[.](1[0-2]|0[0-9])[.]([0-2][0-9]|3[01])$')]),
        ),
    ]
